version: '3'

services:
  app:
    image: auxxxxx/itam_platform202504030232
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development